config/routes.rb
Droplocally::Application.routes.draw do
  get 'sessions/login', :to => 'sessions#login'
  get 'sessions/callback', :to => 'sessions#foursquare_callback'

  get 'home', :to => 'home#index'
  get 'venue/autocomplete', :to => 'venue#autocomplete'
  post 'venue/checkin', :to => 'venue#checkin'
  get 'venues/:fid', :to => 'venue#show'

  post 'venue/:fid/upload', :to => 'file_item#upload'
  get 'venues/:fid/download', :to => 'file_item#download'
  post 'venues/:fid/download', :to => 'file_item#download'
 root :to => 'welcome#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include SessionsHelper

  def index
    @user = current_user
    @page = params[:page]
    @latest_checkins = Checkin.by_user(current_user).desc(:created_at).limit(10)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_checkin.html.erb
<div id= "user_profile_picture" class = "hide" data-url="<%= @user.photo %>"></div>
<div id = "home_checkin" class="listview-container grid-layout">
	<div id = "checkin_container" class = "navbar-form pull-left" style="width:100%;">
	  <%= form_tag('/venue/checkin') do |f| %>
	    <div id = "checkin_form" class = "">
	      <%= hidden_field_tag :user_latitude %>
	      <%= hidden_field_tag :user_longitude %>
	      <%= text_field_tag 'venue_id',nil,
	        placeholder:"Start typing venue name:",
	        class: "input-large disabled" %>
	    </div>
	      
	  <% end %>
	</div>

	<div id = "checkin_map" style="width: 100%;">
		<div id="mapDiv"></div>
		<div id="progress" class="progress hidden"></div>
	</div>
</div>

app/views/home/_folderbar.html.erb
<footer class="win-commandlayout navbar-fixed-bottom">
    <div class="container">
       <div class="row">
          <div class="span6 align-left">
 
             <a class="win-command">
                <span class="win-commandimage win-commandring">&#x0021;</span>
                <span class="win-label">Home</span>
             </a>
 
             <hr class="win-command" />
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xe03e;</span>
                <span class="win-label">Add</span>
             </button>
 
             <button class="win-command bulk_download">
                <span class="win-commandimage win-commandring">&#x0052;</span>
                <span class="win-label">Save</span>
             </button>
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xe125;</span>
                <span class="win-label">Reload</span>
             </button>
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xe1cd;</span>
                <span class="win-label">Previous</span>
             </button>
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xe1ca;</span>
                <span class="win-label">Next</span>
             </button>
 
          </div>
 
          <div class="span6 align-right">
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xe202;</span>
                <span class="win-label">Settings</span>
             </button>
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xE01D;</span>
                <span class="win-label">Download</span>
             </button>
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xE01F;</span>
                <span class="win-label">Upload</span>
             </button>
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xE165;</span>
                <span class="win-label">Send Email</span>
             </button>
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#x0067;</span>
                <span class="win-label">Search</span>
             </button>
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xE001;</span>
                <span class="win-label">Delete</span>
             </button>
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xE15F;</span>
                <span class="win-label">User</span>
             </button>
 
             <button class="win-command">
                <span class="win-commandimage win-commandring">&#xE15E;</span>
                <span class="win-label">Users</span>
             </button>
          </div>
       </div>
    </div>
 </footer>

app/views/home/_friends_checkin.html.erb
<div id = "friends_checkin" class="listview-container grid-layout">
<div class="mediumListIconTextItem" >
	<div class="icon-location mediumListIconTextItem-Image"></div>
    	<div class="mediumListIconTextItem-Detail">
        	<h4>LOcation</h4>
        	<h6>Description</h6>
      	</div>
    </div>
<div>

app/views/home/_latest_checkin.html.erb
<div id = "latest_checkin" class="listview-container grid-layout">
  <% @latest_checkins.each do |checkin| %>
    <% venue = checkin.venue %>
    <div class="mediumListIconTextItem checkin-item"
        data-checkin="<%= checkin.fid %>"
        data-venue="<%= venue.fid %>"
        data-ll="<%= venue.location['lat'] %>,<%= venue.location['lng'] %> "
        data-broadcast= "shout">
	    <div class="icon-location mediumListIconTextItem-Image"></div>
      <div class="mediumListIconTextItem-Detail">
        <% venue = checkin.venue %>
        <% unless venue.nil? %>
          <h4><%= venue.name %></h4>
          <h6>You checked in here
          <%= distance_of_time_in_words_to_now(checkin.created_at.utc) %> ago.</h6>
        <% else %>
          <h4> &lt;Secret place&gt; </h4>
          <h6> Classified - and we can tell you nothing. </h6>
        <% end %>
      </div>
    </div>
  <% end %>
<div>

app/views/home/_top_checkin.html.erb
<div id = "top_checkin" class="listview-container grid-layout">
<div class="mediumListIconTextItem" >
	<div class="icon-location mediumListIconTextItem-Image"></div>
    	<div class="mediumListIconTextItem-Detail">
        	<h4>LOcation</h4>
        	<h6>Description</h6>
      	</div>
    </div>
<div>

app/views/home/index.html.erb
<header>
  <h2>Home View</h2>
  <p>For checkin you can search venue, select your venue among your top places. </p>
</header>

<div>
  <p>
     <a href="<%= home_url %>"
      class="btn btn-large <%= 'btn-primary selected' if @page.nil? %> "
      type="button">
      CheckIn
    </a>
     <a href="<%= home_url %>?page=latest"
        class="btn btn-large <%= 'btn-primary selected' if @page == 'latest' %>" type="button">
        Latest checkins
    </a>
     <a href="<%= home_url %>?page=top"
        class="btn btn-large <%= 'btn-primary selected' if @page == 'top' %>" 
        type="button">Top checkins</button>
     <a href="<%= home_url %>?page=friends"
        class="btn btn-large <%= 'btn-primary selected' if @page == 'friends' %>" type="button">
        Friends checkins
     </a>
  </p>
  <%=
    case @page
    when "latest" then render "latest_checkin"
    when "top" then render "top_checkin"
    when "friends" then render "friends_checkin"
    else render "checkin"
    end %>

    <%= render "shared/checkin_modal" %>
</div>